### ISSUE TITLE
Startup customization doesn’t work.

### ISSUE THREAD

**Issue by tshead** [adamohern/good_kitty#1]
I’ve tried downloading good_kitty-0.1.0.zip and good_kitty-master.zip, but the startup customization described in your howto videos doesn’t run.  The kits themselves work fine - the Make Breakfast and Good Kitty Docs buttons are available and functional, the matte white preset is installed, the preferences work, etc.  Are the videos out of date?  I tried deleting my preferences and disabling every other kit I have installed, but no startup customization.

**Comment by adamohern** [comment]
That's odd. Is there anything suspicious in your event log?

System > Advanced > Event Log

**Comment by tshead** [comment]
Ack, another bit of Python code I was experimenting with was throwing an exception during Modo startup, which prevented good kitty from running.

Sheepishly y'rs,
Tim

**Comment by adamohern** [comment]
Ha! Any time :)
